import {useEffect,useRef,useState} from 'react';
import {Stage,Layer,Rect,Text,Image as CanvasImage,Transformer,Line} from 'react-konva';
import Konva from 'konva';
import type {Element,Page} from '../domain/model';
import {W,H} from '../domain/model';
import {useEditor} from '../store/editor';
import {elementProps,textProps,photoProps,loadAssetImage,loadStaticImage} from './renderer';
export function EditorCanvas({page,width,onTextEdit,onCrop}:{page:Page;width:number;onTextEdit:()=>void;onCrop:()=>void}){
  const transformer=useRef<Konva.Transformer>(null);const stage=useRef<Konva.Stage>(null);const selected=useEditor(s=>s.selected);const select=useEditor(s=>s.select);const update=useEditor(s=>s.updateElement);const scale=width/W;
  const [guides,setGuides]=useState<{x?:number;y?:number}>({});
  useEffect(()=>{if(!stage.current||!transformer.current)return;const nodes=selected.map(id=>stage.current!.findOne(`#${id}`)).filter(Boolean) as Konva.Node[];transformer.current.nodes(nodes);transformer.current.getLayer()?.batchDraw();},[selected,page]);
  function snap(node:Konva.Node){const element=page.elements.find(e=>e.id===node.id());if(!element)return;const xTargets=[0,W/2,W,...page.elements.filter(e=>e.id!==element.id).flatMap(e=>[e.x,e.x+e.width/2,e.x+e.width])];const yTargets=[0,H/2,H,...page.elements.filter(e=>e.id!==element.id).flatMap(e=>[e.y,e.y+e.height/2,e.y+e.height])];const next:{x?:number;y?:number}={};for(const offset of [0,element.width/2,element.width]){const target=xTargets.find(x=>Math.abs(node.x()+offset-x)<8/scale);if(target!==undefined){node.x(target-offset);next.x=target;break;}}for(const offset of [0,element.height/2,element.height]){const target=yTargets.find(y=>Math.abs(node.y()+offset-y)<8/scale);if(target!==undefined){node.y(target-offset);next.y=target;break;}}setGuides(next);}
  return <div className="page-canvas" aria-label="画册编辑画布"><Stage ref={stage} width={width} height={H*scale} scaleX={scale} scaleY={scale} onMouseDown={e=>{if(e.target===e.target.getStage()||e.target.name()==='page-background')select(null);}} onTouchStart={e=>{if(e.target.name()==='page-background')select(null);}}><Layer><Rect name="page-background" width={W} height={H} fill={page.background}/><Pattern pattern={page.pattern}/>{page.elements.map(element=><CanvasElement key={element.id} element={element} onClick={multi=>select(element.id,multi)} onDoubleClick={()=>{select(element.id);if(element.type==='text')onTextEdit();if(element.type==='image')onCrop();}} onDragMove={snap} onCommit={node=>{update(element.id,{x:node.x(),y:node.y(),width:Math.max(20,element.width*node.scaleX()),height:Math.max(20,element.height*node.scaleY()),rotation:node.rotation()});node.scaleX(1);node.scaleY(1);setGuides({});}}/>)}{guides.x!==undefined&&<Line points={[guides.x,0,guides.x,H]} stroke="#e53478" strokeWidth={1/scale} listening={false}/ >}{guides.y!==undefined&&<Line points={[0,guides.y,W,guides.y]} stroke="#e53478" strokeWidth={1/scale} listening={false}/>}<Transformer ref={transformer} rotateEnabled flipEnabled={false} borderStroke="#3185ff" anchorStroke="#3185ff" anchorFill="#fff" anchorSize={7} padding={2} boundBoxFunc={(oldBox,newBox)=>Math.abs(newBox.width)<12||Math.abs(newBox.height)<12?oldBox:newBox}/></Layer></Stage></div>;
}
function Pattern({pattern}:{pattern?:string}){const [image,setImage]=useState<HTMLImageElement>();useEffect(()=>{let alive=true;setImage(undefined);if(pattern)void loadStaticImage(`/reference/${pattern}`).then(img=>{if(alive)setImage(img);}).catch(()=>{});return()=>{alive=false;};},[pattern]);return image?<CanvasImage image={image} width={W} height={H} opacity={.55} listening={false}/>:null;}
function CanvasElement({element,onClick,onDoubleClick,onCommit,onDragMove}:{element:Element;onClick:(multi:boolean)=>void;onDoubleClick:()=>void;onCommit:(node:Konva.Node)=>void;onDragMove:(node:Konva.Node)=>void}){
  const [image,setImage]=useState<HTMLImageElement>();const [failed,setFailed]=useState(false);
  useEffect(()=>{let live=true;setImage(undefined);setFailed(false);if(element.assetId)void loadAssetImage(element.assetId).then(img=>{if(live)setImage(img);}).catch(()=>{if(live)setFailed(true);});return()=>{live=false;};},[element.assetId]);
  const events={draggable:!element.locked,onClick:(e:Konva.KonvaEventObject<MouseEvent>)=>onClick(e.evt.shiftKey),onTap:()=>onClick(false),onDblClick:onDoubleClick,onDblTap:onDoubleClick,onDragStart:()=>onClick(false),onDragMove:(e:Konva.KonvaEventObject<DragEvent>)=>onDragMove(e.target),onDragEnd:(e:Konva.KonvaEventObject<DragEvent>)=>onCommit(e.target),onTransformEnd:(e:Konva.KonvaEventObject<Event>)=>onCommit(e.target)};
  if(element.type==='image')return image?<CanvasImage {...photoProps(element,image)} {...events}/>:<Rect {...elementProps(element)} fill={failed?'#f9b8b8':'#ddd'} {...events}/>;
  if(element.type==='text'||element.type==='sticker')return <Text {...textProps(element)} {...events}/>;
  return <Rect {...elementProps(element)} cornerRadius={element.cornerRadius??0} {...events}/>;
}
