import {useState} from 'react';
import type {Book} from '../domain/model';
import {Modal,Button,ErrorMessage} from '../components/ui';
import {PageThumbnail} from '../components/PageThumbnail';
import {exportBook,downloadBlob,type ExportFormat} from './exportBook';
import {friendlyError} from '../db/repository';
export function ExportDialog({book,open,onClose}:{book:Book;open:boolean;onClose:()=>void}){
  const [format,setFormat]=useState<ExportFormat>('pdf'),[quality,setQuality]=useState(1),[selected,setSelected]=useState<number[]>(book.pages.map((_,i)=>i)),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
  async function run(){setBusy(true);setError('');try{const valid=selected.filter(i=>i<book.pages.length);const blob=await exportBook(book,format,valid,quality,setProgress);const ext=format==='jpg'&&valid.length===1?'jpg':format==='pdf'?'pdf':'zip';downloadBlob(blob,`${book.title.replace(/[<>:"/\\|?*]/g,'_')}.${ext}`);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Modal open={open} onClose={()=>{if(!busy)onClose();}} title="导出 Flipin" description="把回忆保存下来" wide><ErrorMessage message={error}/><fieldset disabled={busy}><div className="segments">{([['pdf','整本 PDF'],['jpg','单页 JPG'],['zip','全部 JPG · ZIP']] as const).map(([value,label])=><Button key={value} className={format===value?'primary':''} onClick={()=>setFormat(value)}>{label}</Button>)}</div><label className="field">清晰度<select value={quality} onChange={e=>setQuality(Number(e.target.value))}><option value={1}>标准 · 1200 × 1696</option><option value={2}>高清 · 2400 × 3392</option><option value={3}>超清 · 3600 × 5088</option></select></label><div className="export-selection"><button onClick={()=>setSelected(book.pages.map((_,i)=>i))}>全选</button><button onClick={()=>setSelected([])}>全不选</button><span>已选 {selected.length} 页</span></div><div className="export-pages">{book.pages.map((page,i)=><button key={page.id} className={selected.includes(i)?'chosen':''} aria-label={`选择第 ${i+1} 页`} onClick={()=>setSelected(selected.includes(i)?selected.filter(x=>x!==i):[...selected,i].sort((a,b)=>a-b))}><PageThumbnail page={page}/><span>{i===0?'封面':i} {selected.includes(i)?'✓':''}</span></button>)}</div></fieldset>{busy&&<div className="export-progress"><span style={{width:`${progress*100}%`}}/></div>}<Button className="primary full" disabled={busy||!selected.length} onClick={()=>void run()}>{busy?`正在渲染… ${Math.round(progress*100)}%`:'确认导出'}</Button></Modal>;
}
