import {useRef,useState} from 'react';
import {useEditor} from '../store/editor';
import {prepareAsset} from '../domain/assets';
import {imageElement,textElement} from '../domain/model';
import {friendlyError} from '../db/repository';
import {Button,ErrorMessage} from '../components/ui';
export function CoverSettingsPanel({onPhotos}:{onPhotos:()=>void}){
  const s=useEditor(),book=s.book!,cover=book.pages[0],photo=cover.elements.find(e=>e.type==='image'),title=cover.elements.find(e=>e.type==='text');
  const input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const colors=['#f5ec30','#eeeae3','#e48af5','#d9eb51','#75a4e1','#ff9658','#f6c9cc','#ffffff','#1a1a1a'];
  function text(value:string,key:'text'|'color'){s.change(b=>{let element=b.pages[0].elements.find(e=>e.type==='text');if(!element){element=textElement('TIME TO FLIPBOOK',{x:180,y:1550,width:840,height:40,fontSize:26,align:'center'});b.pages[0].elements.push(element);}element[key]=value;});}
  async function upload(files:FileList|null){if(!files?.[0])return;setBusy(true);try{const asset=await prepareAsset(files[0]);await s.addAssets([asset]);s.change(b=>{const image=b.pages[0].elements.find(e=>e.type==='image');if(image){image.assetId=asset.id;image.crop={x:.5,y:.5,zoom:1};}else b.pages[0].elements.unshift(imageElement(asset.id,b.coverTemplate==='cutout'?{x:414,y:360,width:372,height:498}:{x:80,y:100,width:1040,height:1300}));});setError('');}catch(e){setError(friendlyError(e));}finally{setBusy(false);if(input.current)input.current.value='';}}
  return <><p className="settings-intro">设置这本画册的封皮、封面照片和标题。</p><p className="field-label">封面模板</p><div className="cover-template-options">{(['basic','cutout'] as const).map(mode=><Button key={mode} aria-pressed={book.coverTemplate===mode} className={book.coverTemplate===mode?'cover-template-card chosen':'cover-template-card'} onClick={()=>s.change(b=>{b.coverTemplate=mode;const image=b.pages[0].elements.find(e=>e.type==='image');if(image)Object.assign(image,mode==='basic'?{x:80,y:100,width:1040,height:1300}:{x:414,y:360,width:372,height:498});})}><span className={`cover-template-sample ${mode}`} style={{backgroundColor:cover.background}}><i/><small>TIME TO FLIPBOOK</small></span><span>{mode==='basic'?'基础封面':'镂空笔记本'}</span></Button>)}</div><p className="field-label">封皮颜色</p><div className="swatches">{colors.map(color=><button key={color} aria-label={`封皮 ${color}`} className={cover.background===color?'chosen':''} style={{backgroundColor:color}} onClick={()=>s.change(b=>{b.pages[0].background=color;})}/>)}</div><label className="field">自定义封皮颜色<input type="color" value={cover.background} onChange={e=>s.change(b=>{b.pages[0].background=e.target.value;})}/></label><p className="field-label">{book.coverTemplate==='cutout'?'镂空区图片':'封面图片'}</p><div className="segments"><Button disabled={busy} onClick={()=>input.current?.click()}>{busy?'正在处理…':'上传图片'}</Button><Button onClick={onPhotos}>从素材库选择</Button></div><input ref={input} type="file" hidden accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void upload(e.target.files)}/>{photo&&<><p className="muted">在封面照片上拖动调整位置，滚轮调整缩放。</p><label className="field">照片模糊度<input type="range" min={0} max={20} step={.5} value={photo.blur??0} onChange={e=>s.change(b=>{const image=b.pages[0].elements.find(e=>e.type==='image');if(image)image.blur=+e.target.value;})}/><span>{photo.blur??0}</span></label><Button className="full" onClick={()=>s.change(b=>{b.pages[0].elements=b.pages[0].elements.filter(e=>e.type!=='image');})}>移除封面照片</Button></>}<label className="field stack">封面标题<input value={title?.text??''} onChange={e=>text(e.target.value,'text')}/></label><label className="field">标题颜色<input type="color" value={title?.color??'#4a3f1a'} onChange={e=>text(e.target.value,'color')}/></label><ErrorMessage message={error}/></>;
}
