import {useRef,useState} from 'react';
import {Plus,X,Upload,ArrowUp,ArrowDown,Copy,Trash2} from 'lucide-react';
import {useEditor} from '../store/editor';
import {layouts} from '../domain/layouts';
import {textElement,imageElement,uid,type Element,type Asset} from '../domain/model';
import {prepareAsset} from '../domain/assets';
import {friendlyError,repository} from '../db/repository';
import {Button,ErrorMessage,IconButton} from '../components/ui';
import {useEffect} from 'react';
export type PanelId='photos'|'layouts'|'text'|'stickers'|'background'|'cover'|'adjust';
const names:Record<PanelId,string>={photos:'上传素材',layouts:'选择排版',text:'文字',stickers:'贴纸',background:'垫底背景',cover:'封面设置',adjust:'调整元素'};
const colors=['#ffffff','#eeeae3','#f5ec30','#e48af5','#d9eb51','#75a4e1','#ff9658','#f6c9cc','#1a1a1a'];
export function EditorPanel({panel,onClose}:{panel:PanelId;onClose:()=>void}){
  const s=useEditor();const book=s.book!;const page=book.pages[s.pageIndex];const selected=page.elements.find(e=>s.selected.includes(e.id));
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[count,setCount]=useState(0),[filter,setFilter]=useState(2);const input=useRef<HTMLInputElement>(null);
  async function upload(files:FileList|null){if(!files)return;setBusy(true);setError('');try{const added=[];for(let i=0;i<files.length;i++){setCount(i+1);added.push(await prepareAsset(files[i]));}await s.addAssets(added);}catch(e){setError(friendlyError(e));}finally{setBusy(false);if(input.current)input.current.value='';}}
  const update=(patch:Partial<Element>)=>{if(selected)s.updateElement(selected.id,patch);};
  const addText=(text:string,size:number,font='Domine')=>s.addElement(textElement(text,{fontSize:size,fontFamily:font}));
  const layer=(direction:number)=>{if(!selected)return;s.change(b=>{const elements=b.pages[s.pageIndex].elements;const i=elements.findIndex(e=>e.id===selected.id);const [element]=elements.splice(i,1);elements.splice(Math.max(0,Math.min(elements.length,i+direction)),0,element);});};
  return <aside className="editor-panel"><div className="panel-grabber"/><header><h2>{names[panel]}</h2><IconButton label="关闭面板" onClick={onClose}><X size={17}/></IconButton></header><ErrorMessage message={error}/><div className="panel-body">
    {panel==='photos'&&<><p className="muted">点击照片，添加到当前页</p><Button className="full" disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/>{busy?`正在处理 ${count} 张…`:'上传照片'}</Button><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif" hidden onChange={e=>void upload(e.target.files)}/><div className="asset-grid">{book.assets.map(asset=><AssetTile key={asset.id} asset={asset} used={page.elements.some(e=>e.assetId===asset.id)} onClick={()=>s.addElement(imageElement(asset.id,{x:120,y:180,width:900,height:1000}))}/>)}</div>{!book.assets.length&&<p className="empty-panel">还没有照片<br/>上传照片开始制作。</p>}</>}
    {panel==='layouts'&&<><div className="segments">{[1,2,3,4].map(n=><Button key={n} className={filter===n?'primary':''} onClick={()=>setFilter(n)}>{n} 图</Button>)}</div><div className="layout-grid">{layouts.filter(l=>l.minImages===filter).map(l=><button key={l.id} aria-label={l.name} title={l.name} className={page.layoutId===l.id?'chosen':''} onClick={()=>s.layout(l.id)}><span className="layout-mini">{l.slots.map((slot,i)=><i key={i} style={{left:`${slot.x*100}%`,top:`${slot.y*100}%`,width:`${slot.width*100}%`,height:`${slot.height*100}%`}}/>)}</span><small>{l.name}</small></button>)}</div><p className="muted">替换排版会保留照片和文字。</p></>}
    {panel==='text'&&<>{selected?.type==='text'?<><textarea aria-label="文字内容" value={selected.text} onChange={e=>update({text:e.target.value})} rows={3}/><label className="field">字体<select value={selected.fontFamily} onChange={e=>update({fontFamily:e.target.value})}><option value="Domine">Domine · 杂志衬线</option><option value="Arial">Arial · 现代无衬线</option><option value="Georgia">Georgia · 经典</option><option value="KaiTi">楷体 · 手写</option><option value="sans-serif">黑体</option></select></label><label className="field">字号<input type="range" min={16} max={240} value={selected.fontSize} onChange={e=>update({fontSize:+e.target.value})}/><span>{selected.fontSize}</span></label><label className="field">颜色<input type="color" value={selected.color} onChange={e=>update({color:e.target.value})}/></label><div className="segments"><Button className={selected.fontWeight===700?'primary':''} onClick={()=>update({fontWeight:selected.fontWeight===700?400:700})}><b>B</b></Button>{(['left','center','right'] as const).map((align,i)=><Button key={align} className={selected.align===align?'primary':''} onClick={()=>update({align})}>{['左','中','右'][i]}</Button>)}</div></>:<p className="muted">选择一段文字，或者添加新的文字</p>}<div className="text-presets"><button onClick={()=>addText('写下这一刻',100)}>添加标题 <Plus size={16}/></button><button onClick={()=>addText('一些值得记住的小事',54)}>添加副标题 <Plus size={16}/></button><button onClick={()=>addText('你的段落文字',36,'sans-serif')}>添加正文 <Plus size={16}/></button><button onClick={()=>addText(new Date().toLocaleDateString('zh-CN'),28,'Arial')}>日期 / 注释 <Plus size={16}/></button></div></>}
    {panel==='stickers'&&<><p className="muted">给回忆加一点小装饰</p><div className="sticker-grid">{['★','♡','✿','↗','✦','♥','☀','✈','✽','☻','❀','➜','✉','♫','☁','✧'].map(sticker=><button key={sticker} onClick={()=>s.addElement({...textElement(sticker,{fontSize:180,width:240,height:260,fontFamily:'Arial',color:'#e63457'}),type:'sticker'})}>{sticker}</button>)}</div><Button className="full" onClick={()=>s.addElement({id:uid(),type:'shape',x:280,y:180,width:460,height:90,rotation:-7,opacity:.65,color:'#ddd0a4'})}>添加纸胶带</Button><Button className="full" onClick={()=>s.addElement({id:uid(),type:'shape',x:140,y:250,width:800,height:1050,rotation:3,opacity:1,color:'#fff',shadow:true})}>添加拍立得底纸</Button></>}
    {panel==='background'&&<><label className="field">当前页面背景<input type="color" value={page.background} onChange={e=>s.change(b=>{b.pages[s.pageIndex].background=e.target.value;})}/></label><div className="swatches">{colors.map(color=><button key={color} aria-label={`背景 ${color}`} style={{backgroundColor:color}} className={page.background===color?'chosen':''} onClick={()=>s.change(b=>{b.pages[s.pageIndex].background=color;})}/>)}</div><p className="field-label">纸张与纹理</p><div className="background-grid">{['','bg-dots.jpg','bg-grid.jpg','bg2.jpg','bg3.jpg','bg4.jpg','bg5.jpg'].map((name,i)=><button key={name} className={page.pattern===name?'chosen':''} onClick={()=>s.change(b=>{b.pages[s.pageIndex].pattern=name||undefined;})} style={name?{backgroundImage:`url(/reference/${name})`}:{}}>{i===0?'纯色':['','波点','格纹','纸张','织物','纹理','牛皮纸'][i]}</button>)}</div><label className="field">画册外底<input type="color" value={book.workspaceBackground} onChange={e=>s.change(b=>{b.workspaceBackground=e.target.value;})}/></label></>}
    {panel==='cover'&&<><p className="field-label">封面模板</p><div className="segments"><Button className={book.coverTemplate==='basic'?'primary':''} onClick={()=>s.change(b=>{b.coverTemplate='basic';const image=b.pages[0].elements.find(e=>e.type==='image');if(image)Object.assign(image,{x:80,y:100,width:1040,height:1300});})}>基础封面</Button><Button className={book.coverTemplate==='cutout'?'primary':''} onClick={()=>s.change(b=>{b.coverTemplate='cutout';const image=b.pages[0].elements.find(e=>e.type==='image');if(image)Object.assign(image,{x:414,y:360,width:372,height:498});})}>镂空笔记本</Button></div><p className="field-label">封皮颜色</p><div className="swatches">{colors.map(color=><button key={color} aria-label={`封皮 ${color}`} style={{backgroundColor:color}} onClick={()=>s.change(b=>{b.pages[0].background=color;})}/>)}</div><label className="field">自定义颜色<input type="color" value={book.pages[0].background} onChange={e=>s.change(b=>{b.pages[0].background=e.target.value;})}/></label><label className="field stack">封面标题<input value={book.pages[0].elements.find(e=>e.type==='text')?.text??''} onChange={e=>s.change(b=>{const text=b.pages[0].elements.find(e=>e.type==='text');if(text)text.text=e.target.value;else b.pages[0].elements.push(textElement(e.target.value));})}/></label><Button className="full" onClick={()=>s.setPage(0)}>回到封面编辑</Button><p className="muted">选择封面照片后，可替换、拖动和裁剪。</p></>}
    {panel==='adjust'&&(selected?<><label className="field">旋转<input type="range" min={-180} max={180} value={selected.rotation} onChange={e=>update({rotation:+e.target.value})}/><span>{Math.round(selected.rotation)}°</span></label><label className="field">透明度<input type="range" min={.05} max={1} step={.05} value={selected.opacity} onChange={e=>update({opacity:+e.target.value})}/></label><label className="field">锁定<input type="checkbox" checked={!!selected.locked} onChange={e=>update({locked:e.target.checked})}/></label><div className="segments"><Button onClick={()=>layer(-1)}><ArrowDown size={16}/>下移</Button><Button onClick={()=>layer(1)}><ArrowUp size={16}/>上移</Button></div>{selected.type==='image'&&<><label className="field">适配<select value={selected.fit??'cover'} onChange={e=>update({fit:e.target.value as 'cover'|'contain'})}><option value="cover">填充</option><option value="contain">完整显示</option></select></label><label className="field">图片描边<input type="range" min={0} max={40} value={selected.border??0} onChange={e=>update({border:+e.target.value})}/></label><label className="field">描边颜色<input type="color" value={selected.borderColor??'#ffffff'} onChange={e=>update({borderColor:e.target.value})}/></label><label className="field">阴影<input type="checkbox" checked={!!selected.shadow} onChange={e=>update({shadow:e.target.checked})}/></label></>}<div className="segments"><Button onClick={s.duplicateSelected}><Copy size={16}/>复制</Button><Button className="danger" onClick={s.deleteSelected}><Trash2 size={16}/>删除</Button></div></>:<p className="empty-panel">先在页面上选择一个元素</p>)}
  </div></aside>;
}
function AssetTile({asset,used,onClick}:{asset:Asset;used:boolean;onClick:()=>void}){const [url,setUrl]=useState('');useEffect(()=>{let url='',active=true;void repository.getAsset(asset.id).then(a=>{if(a&&active){url=URL.createObjectURL(a.thumbnail);setUrl(url);}}).catch(()=>{});return()=>{active=false;URL.revokeObjectURL(url);};},[asset.id]);return <button title={asset.name} onClick={onClick}><img src={url} alt={asset.name}/>{used&&<span>✓</span>}</button>;}
