import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Plus,X,ChevronRight} from 'lucide-react';
import {type StoredAsset,type ThemeId,newBook,uid} from '../domain/model';
import {prepareAsset,assetMetadata} from '../domain/assets';
import {autoLayout} from '../domain/layouts';
import {repository,friendlyError} from '../db/repository';
import {Modal,Button,ErrorMessage} from '../components/ui';
import {Bookshelf} from './Bookshelf';
export function Create(){
  const [step,setStep]=useState(1),[theme,setTheme]=useState<ThemeId>('scrapbook'),[assets,setAssets]=useState<StoredAsset[]>([]),[error,setError]=useState(''),[processing,setProcessing]=useState(false),[progress,setProgress]=useState(''),[examples,setExamples]=useState(false);
  const input=useRef<HTMLInputElement>(null);const navigate=useNavigate();
  async function upload(files:FileList|File[]|null){if(!files)return;setError('');setProcessing(true);const batch=Array.from(files);if(batch.length+assets.length>50){setError('一本最多放 50 张照片，请减少选择。');setProcessing(false);return;}const added:StoredAsset[]=[],uploadBatch={id:uid(),at:Date.now()};try{for(let i=0;i<batch.length;i++){setProgress(`正在整理照片 ${i+1} / ${batch.length}`);added.push(await prepareAsset(batch[i],uploadBatch));}setAssets(prev=>[...prev,...added]);}catch(e){setError(friendlyError(e));}finally{setProcessing(false);setProgress('');if(input.current)input.current.value='';}}
  async function generate(){setStep(3);setError('');try{setProgress('正在挑选版式…');const count=(await repository.list()).length;const book=autoLayout(newBook(`FLIPBOOK #${String(count).padStart(3,'0')}`,theme,assets.map(assetMetadata)),assets.map(assetMetadata));setProgress('正在装订画册…');await repository.create(book,assets);navigate(`/editor/${book.id}`,{replace:true});}catch(e){setStep(2);setError(friendlyError(e));}}
  return <><Bookshelf creating/><Modal open onClose={()=>{if(step!==3&&!processing)navigate('/');}} title={step===1?'今天做本什么样的？':step===2?'往书里装点内容':'Flipbook 正在装订中...'} description={step===1?'选一种感觉，Flipbook 帮你搭个调子':step===2?'推荐 8–20 张照片，最多可以放 50 张':'好东西值得等一小会儿'}><div className="wizard-progress">{[1,2,3].map(n=><span key={n} className={n<=step?'on':''}/>)}</div><ErrorMessage message={error}/>{step===1?<><div className="theme-options"><label><input type="radio" checked={theme==='scrapbook'} onChange={()=>setTheme('scrapbook')}/>高饱和拼贴</label><label><input type="radio" checked={theme==='editorial'} onChange={()=>setTheme('editorial')}/>氛围感杂志</label></div><div className="theme-preview"><img src={`/reference/${theme==='scrapbook'?'style01':'style02'}.jpg`} alt={theme==='scrapbook'?'高饱和拼贴示例':'氛围感杂志示例'}/></div><button className="examples-link" onClick={()=>setExamples(true)}>点我查看更多示例页 <ChevronRight size={13}/></button><div className="actions"><Button onClick={()=>navigate('/')}>取消</Button><Button className="primary" onClick={()=>setStep(2)}>就它了</Button></div></>:step===2?<><div className={`upload-zone ${assets.length?'filled':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!processing)void upload(e.dataTransfer.files);}}>{assets.length?<div className="upload-grid">{assets.map((asset,i)=><UploadThumb key={asset.id} asset={asset} remove={()=>setAssets(assets.filter((_,n)=>n!==i))}/>)}<button aria-label="继续添加照片" className="upload-add" disabled={processing} onClick={()=>input.current?.click()}><Plus/></button></div>:<button className="upload-empty" disabled={processing} onClick={()=>input.current?.click()}><Plus size={36} strokeWidth={1.4}/><span>还是空的，点这里加照片吧</span><small>也可以把照片拖到这里</small></button>}</div><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" multiple hidden aria-label="上传照片" onChange={e=>void upload(e.target.files)}/><div className="upload-count">{processing?progress:`已选 ${assets.length} / 50`}</div><div className="actions"><Button disabled={processing} onClick={()=>setStep(1)}>上一步</Button><Button className="primary" disabled={processing||assets.length<3} onClick={()=>void generate()}>选好了</Button></div>{assets.length>0&&assets.length<3&&<p className="muted centered">至少选择 3 张照片</p>}</>:<div className="generation"><div className="binding-animation"><span/><span/><span/><span/><span/></div><p>{progress}</p></div>}</Modal><Modal open={examples} onClose={()=>setExamples(false)} title="翻翻看，找到你的感觉" wide><div className="example-gallery"><img src="/reference/style01.jpg" alt="拼贴示例"/><img src="/reference/style02.jpg" alt="杂志示例"/></div></Modal></>;
}
function UploadThumb({asset,remove}:{asset:StoredAsset;remove:()=>void}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(asset.thumbnail);setUrl(u);return()=>URL.revokeObjectURL(u);},[asset]);return <div className="upload-thumb"><img src={url} alt={asset.name}/><button aria-label={`移除 ${asset.name}`} onClick={remove}><X size={12}/></button></div>;}
