import {useEffect,useRef,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ChevronLeft,ChevronRight,Undo2,Redo2,Eye,Upload,Images,Grid2X2,Type,Sun,Plus,Sticker,Maximize2,Minimize2,Copy,Trash2,Crop,Replace,BookOpen,Palette,Check,MoreHorizontal} from 'lucide-react';
import {repository,friendlyError} from '../db/repository';
import {useEditor} from '../store/editor';
import {EditorCanvas} from '../editor/EditorCanvas';
import {clearImageCache} from '../editor/renderer';
import {PageThumbnail} from '../components/PageThumbnail';
import {Button,IconButton,Loading,ErrorMessage,Modal} from '../components/ui';
import {EditorPanel,type PanelId} from '../panels/EditorPanel';
import {ExportDialog} from '../export/ExportDialog';
import {prepareAsset} from '../domain/assets';
export function Editor(){
  const {bookId}=useParams();const navigate=useNavigate();const s=useEditor();const [loading,setLoading]=useState(true),[error,setError]=useState(''),[panel,setPanel]=useState<PanelId|null>(null),[wide,setWide]=useState(false),[exporting,setExporting]=useState(false),[deleting,setDeleting]=useState(false),[pageMenu,setPageMenu]=useState(false),[cropOpen,setCropOpen]=useState(false),[crop,setCrop]=useState({x:.5,y:.5,zoom:1}),[viewWidth,setViewWidth]=useState(360),[viewHeight,setViewHeight]=useState(500);
  const workspace=useRef<HTMLDivElement>(null);const replaceInput=useRef<HTMLInputElement>(null);const dragged=useRef<number|null>(null);
  useEffect(()=>{let live=true;setLoading(true);void repository.get(bookId!).then(book=>{if(live){s.load(book);setLoading(false);}}).catch(e=>{setError(friendlyError(e));setLoading(false);});return()=>{live=false;void useEditor.getState().flush().catch(()=>{});clearImageCache();};},[bookId]);
  useEffect(()=>{if(!workspace.current)return;const observer=new ResizeObserver(entries=>{setViewWidth(entries[0].contentRect.width);setViewHeight(entries[0].contentRect.height);});observer.observe(workspace.current);return()=>observer.disconnect();},[loading,wide,panel]);
  useEffect(()=>{function key(e:KeyboardEvent){if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable=true]')||document.querySelector('[role=dialog]'))return;const state=useEditor.getState();const mod=e.ctrlKey||e.metaKey;const key=e.key.toLowerCase();if(mod&&key==='z'){e.preventDefault();if(e.shiftKey)state.redo();else state.undo();}else if(mod&&['c','v','d'].includes(key)){e.preventDefault();if(key==='c')state.copy();if(key==='v')state.paste();if(key==='d')state.duplicateSelected();}else if(key==='delete'||key==='backspace'){e.preventDefault();state.deleteSelected();}else if(key==='escape'){state.select(null);setPanel(null);}else if(e.key.startsWith('Arrow')&&state.selected.length){e.preventDefault();const d=e.shiftKey?10:1;state.change(b=>{for(const element of b.pages[state.pageIndex].elements){if(state.selected.includes(element.id)&&!element.locked){element.x+=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0;element.y+=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0;}}});}}
    function exit(e:BeforeUnloadEvent){if(useEditor.getState().status!=='saved'){void useEditor.getState().flush().catch(()=>{});e.preventDefault();}}
    function visibility(){if(document.visibilityState==='hidden')void useEditor.getState().flush().catch(()=>{});}
    window.addEventListener('keydown',key);window.addEventListener('beforeunload',exit);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('beforeunload',exit);document.removeEventListener('visibilitychange',visibility);};},[]);
  async function leave(path:string){try{await s.flush();navigate(path);}catch(e){setError(friendlyError(e));}}
  async function replace(files:FileList|null){if(!files?.[0]||!s.selected[0])return;try{const asset=await prepareAsset(files[0]);await s.addAssets([asset]);s.updateElement(s.selected[0],{assetId:asset.id,crop:{x:.5,y:.5,zoom:1}});}catch(e){setError(friendlyError(e));}finally{if(replaceInput.current)replaceInput.current.value='';}}
  if(loading)return <main className="phone-shell"><Loading/></main>;if(!s.book||error&&s.book.id!==bookId)return <main className="phone-shell"><ErrorMessage message={error}/><Button onClick={()=>navigate('/')}>返回书架</Button></main>;
  const book=s.book,page=book.pages[s.pageIndex],selected=page.elements.find(e=>s.selected.includes(e.id));const pair=s.pageIndex===0?-1:s.pageIndex%2===1?s.pageIndex+1:s.pageIndex-1;const pairPage=book.pages[pair];const canvasWidth=Math.min(wide?340:160,(viewWidth-42)/(pairPage?2:1),Math.max(100,viewHeight-235)/1.4133);
  const tools=[['photos',Images,'素材库'],['layouts',Grid2X2,'模版'],['text',Type,'文字'],['stickers',Sticker,'贴纸'],['adjust',Sun,'调整']] as const;
  function openCrop(){if(selected?.type==='image'){setCrop(selected.crop??{x:.5,y:.5,zoom:1});setCropOpen(true);}}
  return <main className={`phone-shell studio ${wide?'expanded':''}`}><header className="studio-header"><IconButton label="返回书架" onClick={()=>void leave('/')}><ChevronLeft size={21}/></IconButton><input className="editor-title" aria-label="画册名称" value={book.title} onChange={e=>s.change(b=>{b.title=e.target.value;})}/><IconButton label={wide?'收起工作区':'展开工作区'} onClick={()=>setWide(!wide)}>{wide?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</IconButton></header><ErrorMessage message={error||s.error}/>
  <div className="editor-workspace" ref={workspace} style={{backgroundColor:book.workspaceBackground}}><div className="workspace-toolbar"><div className="toolbar-pill"><IconButton label="撤销" disabled={!s.past.length} onClick={s.undo}><Undo2 size={16}/></IconButton><IconButton label="重做" disabled={!s.future.length} onClick={s.redo}><Redo2 size={16}/></IconButton></div><div className="toolbar-pill"><IconButton label="封面设置" onClick={()=>setPanel(panel==='cover'?null:'cover')}><BookOpen size={16}/></IconButton><IconButton label="垫底背景" onClick={()=>setPanel(panel==='background'?null:'background')}><Palette size={16}/></IconButton><IconButton label="翻页预览" onClick={()=>void leave(`/preview/${book.id}`)}><Eye size={16}/></IconButton><IconButton label="导出 Flipin" onClick={()=>setExporting(true)}><Upload size={16}/></IconButton></div></div>
    <div className="save-status" role="status">{s.status==='saved'?<><Check size={10}/>已保存</>:s.status==='saving'?'保存中…':<button onClick={()=>void s.flush().catch(()=>{})}>保存失败，点此重试</button>}</div>
    {selected&&<div className="context-toolbar">{selected.type==='image'&&<><IconButton label="替换图片" onClick={()=>replaceInput.current?.click()}><Replace size={16}/></IconButton><IconButton label="裁剪图片" onClick={openCrop}><Crop size={16}/></IconButton></>}<IconButton label="复制元素" onClick={s.duplicateSelected}><Copy size={16}/></IconButton><IconButton label="删除元素" onClick={s.deleteSelected}><Trash2 size={16}/></IconButton></div>}
    <input ref={replaceInput} type="file" hidden accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={e=>void replace(e.target.files)}/>
    <div className={`spread-area ${panel?'panel-open':''}`}><div className="spread" style={{flexDirection:s.pageIndex>0&&s.pageIndex%2===0?'row-reverse':'row'}}><EditorCanvas page={page} width={Math.max(90,canvasWidth)} onTextEdit={()=>setPanel('text')} onCrop={openCrop}/>{pairPage&&<button className="paired-page" aria-label={`编辑第 ${pair} 页`} style={{width:canvasWidth}} onClick={()=>s.setPage(pair)}><PageThumbnail page={pairPage} scale={.5}/></button>}{pairPage&&<div className="spine-shadow"/>}</div></div>
    <div className="page-navigation"><IconButton label="上一页" disabled={s.pageIndex===0} onClick={()=>s.setPage(s.pageIndex-1)}><ChevronLeft size={17}/></IconButton><button onClick={()=>setPageMenu(true)}>{s.pageIndex===0?'封面':`${s.pageIndex} / ${book.pages.length-1}`} <MoreHorizontal size={13}/></button><IconButton label="下一页" disabled={s.pageIndex===book.pages.length-1} onClick={()=>s.setPage(s.pageIndex+1)}><ChevronRight size={17}/></IconButton></div>
    <div className="page-strip">{book.pages.map((p,i)=><button key={p.id} draggable={i!==0} aria-label={i===0?'封面':`第 ${i} 页`} className={i===s.pageIndex?'selected':''} onClick={()=>s.setPage(i)} onDragStart={()=>dragged.current=i} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged.current!==null)s.reorderPage(dragged.current,i);dragged.current=null;}}><PageThumbnail page={p}/><span>{i===0?'封面':i}</span></button>)}<button className="add-page" aria-label="新建页面" onClick={s.addPage}><Plus size={19}/></button></div>
  </div><nav className="editor-tools">{tools.map(([id,Icon,label])=><button key={id} className={panel===id?'selected':''} onClick={()=>setPanel(panel===id?null:id)}><Icon size={21} strokeWidth={1.6}/><span>{label}</span></button>)}</nav>{panel&&<EditorPanel panel={panel} onClose={()=>setPanel(null)}/>}
  <ExportDialog book={book} open={exporting} onClose={()=>setExporting(false)}/><Modal open={pageMenu} onClose={()=>setPageMenu(false)} title="页面操作"><div className="menu-list"><Button onClick={()=>{s.addPage();setPageMenu(false);}}>添加空白页</Button><Button disabled={s.pageIndex===0} onClick={()=>{s.duplicatePage();setPageMenu(false);}}>复制当前页</Button><Button disabled={s.pageIndex===0} onClick={()=>{s.reorderPage(s.pageIndex,Math.max(1,s.pageIndex-1));setPageMenu(false);}}>向前移动一页</Button><Button disabled={s.pageIndex===0||s.pageIndex===book.pages.length-1} onClick={()=>{s.reorderPage(s.pageIndex,s.pageIndex+1);setPageMenu(false);}}>向后移动一页</Button><Button disabled={s.pageIndex===0} className="danger" onClick={()=>{setPageMenu(false);setDeleting(true);}}>删除当前页</Button></div></Modal><Modal open={deleting} onClose={()=>setDeleting(false)} title="删除这一页？" description="页面上的内容会一起移除，可以通过撤销恢复。"><div className="actions"><Button onClick={()=>setDeleting(false)}>取消</Button><Button className="danger" onClick={()=>{s.removePage();setDeleting(false);}}>删除</Button></div></Modal>
  <Modal open={cropOpen} onClose={()=>setCropOpen(false)} title="裁剪图片" description="调整照片在画框中的位置"><label className="field">水平<input type="range" min={0} max={1} step={.01} value={crop.x} onChange={e=>setCrop({...crop,x:+e.target.value})}/></label><label className="field">垂直<input type="range" min={0} max={1} step={.01} value={crop.y} onChange={e=>setCrop({...crop,y:+e.target.value})}/></label><label className="field">缩放<input type="range" min={1} max={4} step={.05} value={crop.zoom} onChange={e=>setCrop({...crop,zoom:+e.target.value})}/></label><div className="actions"><Button onClick={()=>setCropOpen(false)}>取消</Button><Button className="primary" onClick={()=>{if(selected)s.updateElement(selected.id,{crop});setCropOpen(false);}}>确定</Button></div></Modal>
  </main>;
}



