import {forwardRef,useEffect,useRef,useState} from 'react';
import HTMLFlipBook from 'react-pageflip';
import {useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {ChevronLeft,ChevronRight,Maximize2,Upload,Pencil} from 'lucide-react';
import {type Book} from '../domain/model';
import {repository,friendlyError} from '../db/repository';
import {renderPage} from '../editor/renderer';
import {IconButton,Loading,ErrorMessage,Button} from '../components/ui';
import {ExportDialog} from '../export/ExportDialog';
const FlipPage=forwardRef<HTMLDivElement,{src:string;cover:boolean;index:number}>(({src,cover,index},ref)=><div ref={ref} className="flip-page" data-density={cover?'hard':'soft'}><img src={src} alt={index===0?'封面':`第 ${index} 页`}/></div>);
export function Preview(){
  const {bookId}=useParams();const [query]=useSearchParams();const navigate=useNavigate();const [book,setBook]=useState<Book>(),[urls,setUrls]=useState<string[]>([]),[error,setError]=useState(''),[progress,setProgress]=useState(0),[index,setIndex]=useState(0),[exporting,setExporting]=useState(query.has('export'));
  const flip=useRef<any>(null),shell=useRef<HTMLDivElement>(null);
  useEffect(()=>{let live=true;const urls:string[]=[];void repository.get(bookId!).then(async b=>{if(!live)return;setBook(b);for(let i=0;i<b.pages.length;i++){const blob=await renderPage(b.pages[i],{scale:.6});if(!live)return;urls.push(URL.createObjectURL(blob));setProgress(i+1);}if(live)setUrls([...urls]);}).catch(e=>{if(live)setError(friendlyError(e));});return()=>{live=false;urls.forEach(URL.revokeObjectURL);};},[bookId]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(document.querySelector('[role=dialog]'))return;if(e.key==='ArrowRight')flip.current?.pageFlip().flipNext();if(e.key==='ArrowLeft')flip.current?.pageFlip().flipPrev();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  return <main ref={shell} className="phone-shell preview-shell" style={{background:book?.workspaceBackground??'#e9eaec'}}><header className="studio-header"><IconButton label="返回编辑" onClick={()=>navigate(`/editor/${bookId}`)}><ChevronLeft size={21}/></IconButton><span>{book?.title??'FLIPBOOK'}</span><div className="flex"><IconButton label="全屏" onClick={()=>{void (document.fullscreenElement?document.exitFullscreen():shell.current?.requestFullscreen())?.catch(e=>setError(friendlyError(e)));}}><Maximize2 size={17}/></IconButton><IconButton label="导出 Flipbook" onClick={()=>setExporting(true)}><Upload size={17}/></IconButton></div></header><ErrorMessage message={error}/>{error?<Button onClick={()=>navigate('/')}>返回书架</Button>:!urls.length?<Loading text={`正在制作预览… ${progress} / ${book?.pages.length??'—'}`}/>:<><div className={`flip-stage ${index===0?'is-cover':' '}`}><HTMLFlipBook ref={flip} width={180} height={254} size="stretch" minWidth={130} maxWidth={210} minHeight={184} maxHeight={297} maxShadowOpacity={.3} showCover mobileScrollSupport={true} className="flip-book" style={{}} startPage={0} drawShadow flippingTime={750} usePortrait startZIndex={0} autoSize clickEventForward useMouseEvents swipeDistance={25} showPageCorners disableFlipByClick={false} onFlip={e=>setIndex(e.data)}>{urls.map((src,i)=><FlipPage key={src} src={src} index={i} cover={i===0}/>)}</HTMLFlipBook></div><div className="preview-navigation"><IconButton label="上一页" disabled={index===0} onClick={()=>flip.current?.pageFlip().flipPrev()}><ChevronLeft/></IconButton><span>{index+1} / {urls.length}</span><IconButton label="下一页" disabled={index===urls.length-1} onClick={()=>flip.current?.pageFlip().flipNext()}><ChevronRight/></IconButton></div><p className="preview-hint">轻拖书页一角，翻开下一段回忆</p><Button className="back-to-edit" onClick={()=>navigate(`/editor/${bookId}`)}><Pencil size={15}/>继续编辑</Button></>}{book&&<ExportDialog book={book} open={exporting} onClose={()=>setExporting(false)}/>}</main>;
}

